POP R0; // POP CALCULATE_LOCAL_originPieceColor
POP R0; // POP CALCULATE_LOCAL_bestGameValue
POP R0; // POP CALCULATE_LOCAL_originPlayerIsInCheck
POP R0; // POP CALCULATE_LOCAL_winGameValue
POP R0; // POP CALCULATE_LOCAL_singlePawnJump
POP R0; // POP CALCULATE_LOCAL_originSquareIndex
POP R0; // POP CALCULATE_LOCAL_originSquareValue
POP R0; // POP CALCULATE_LOCAL_movedOriginPieceValue
POP R0; // POP CALCULATE_LOCAL_colorlessOriginPieceValue
POP R0; // POP CALCULATE_LOCAL_originPieceIsOnOriginalSquare
POP R0; // POP CALCULATE_LOCAL_originPieceIsAPawn
POP R0; // POP CALCULATE_LOCAL_originPieceIsAKing
POP R0; // POP CALCULATE_LOCAL_originPieceIsSlidey
POP R0; // POP CALCULATE_LOCAL_moveDirectionNumber;
POP R0; // POP CALCULATE_LOCAL_moveDirectionIndex;
POP R0; // POP CALCULATE_LOCAL_targetSquareIndex;
POP R0; // POP CALCULATE_LOCAL_targetSquareValue;
POP R0; // POP CALCULATE_LOCAL_otherSquareOriginIndex;
POP R0; // POP CALCULATE_LOCAL_otherSquareTargetIndex;
RET;